// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqjwnawdnredapwgdcws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxanduYXdkbnJlZGFwd2dkY3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTU4NTQsImV4cCI6MjA2MTI5MTg1NH0.0fHkD3K02-EAnpksqKqdgWZ88fdDz1m3P87KdPF9OjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);