
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configure your self-hosted Supabase instance here
const SUPABASE_URL = process.env.VITE_SUPABASE_URL || "https://sjuhaqgbdscxzzbtuxew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqdWhhcWdiZHNjeHp6YnR1eGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODY0MjMsImV4cCI6MjA2MTQ2MjQyM30.6ltD_cAxzKgFiGZzFs1ukhuQEywG0m0WwBddo9QpGK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
